name := "scalax-collection"

organization := "com.daodecode"

scalaVersion := "2.12.2"

crossScalaVersions := Seq("2.10.6", "2.11.11", scalaVersion.value)

def scalacOptionsVersion(scalaBinVersion: String) = {
  Seq(
    "-Xlint",
    "-unchecked",
    "-deprecation",
    "-Xfatal-warnings",
    "-Ywarn-inaccessible",
    "-Ywarn-dead-code",
    "-Ywarn-adapted-args",
    "-Ywarn-nullary-unit",
    "-feature",
    "-language:postfixOps",
    "-language:implicitConversions",
    "-encoding", "UTF-8"
  ) ++ {
    scalaBinVersion match {
      case "2.11" | "2.12" => Seq("-Ywarn-unused", "-Ywarn-unused-import")
      case _ => Nil
    }
  }
}

scalacOptions := scalacOptionsVersion(scalaBinaryVersion.value)

libraryDependencies += "org.scalatest" %% "scalatest" % "3.0.3" % "test"

scalacOptions in (Compile, console) := scalacOptions.value.filterNot(_ == "-Ywarn-unused-import")

// code generated by sbt-testdoc needs that to compile
scalacOptions in Test := scalacOptions.value.filterNot(_ == "-Ywarn-unused")

initialCommands in console := "import com.daodecode.scalax.collection.extensions._"

tutSettings

tutSourceDirectory := file(".") / "docs"

tutTargetDirectory := file(".")
