//sbt-doctest and mdoc settings

libraryDependencies += "org.scalacheck" %% "scalacheck" % "1.17.0" % "test"

doctestTestFramework := DoctestTestFramework.ScalaTest

// code generated by sbt-doctest needs that to compile
Test / scalacOptions := scalacOptions.value.filterNot(_ == "-Xfatal-warnings")



