//sbt-doctest and mdoc settings

libraryDependencies +=
  "org.scalacheck" %% "scalacheck" % "1.15.3" % "test"

doctestTestFramework := DoctestTestFramework.ScalaTest

// code generated by sbt-doctest needs that to compile
scalacOptions in Test := scalacOptions.value.filterNot(_ == "-Xfatal-warnings")

enablePlugins(MdocPlugin)

mdocIn := file(".") / "docs"

mdocOut := file(".")