//sbt-doctest and tut settings

libraryDependencies +=
  "org.scalacheck" %% "scalacheck" % "1.13.5" % "test"

doctestTestFramework := DoctestTestFramework.ScalaTest

// code generated by sbt-doctest needs that to compile
scalacOptions in Test := scalacOptions.value.filterNot(_ == "-Ywarn-unused")

enablePlugins(TutPlugin)

tutSourceDirectory := file(".") / "docs"

tutTargetDirectory := file(".")